### ISSUE TITLE
Abolished Daylight Saving may have affected Timezones in Brazil

### ISSUE THREAD

**Issue by jvgirard** [marcoancona/MineTime#242] opened 2020-10-21 20:31 UTC
On 2019 Daylight Saving was abolished from all Brazilian Timezones. Last Sunday (18/10/20) it would have started and it seems that MineTime updated all my calendar events.
My agenda is synced with Office 365 (Outlook) and there the correct time for the events are shown.

**Comment by marcoancona** [comment] 2020-10-27 14:07
Hi @jvgirard, what version of MineTime are you using? If you are using MineTime since a while, please try to use the "Reset data" button in your account settings. This will trigger a new full synchronization with the server.

**Comment by jvgirard** [comment] 2020-11-05 14:07
I'm on the latest version at `1.8.10`. Tried first relinking my account, than erasing it and then linking again. Now pressed the `Reset Data`. All attempts lead to my calendar still be desynchronized.
On the last few weeks I've noticed that only past events remains with the wrong time being displayed. New events have the correct time attached.
This issue impacts me because several older events were not created by me, but others.

**Comment by kamushadenes** [comment] 2020-11-16 14:30
I have the same issue, all my events are showing as 1 hour earlier than they actually are.

**Comment by mikaelmello** [comment] 2020-12-02 03:12
+1 on this issue, it is really annoying and makes the app unusable for Brazilians.

After digging around the source code, I believe the root cause for this problem is a dependency on an outdated version of `pytz`. I have found that events saved in UTC do not have a problem, but events saved in America/Sao_Paulo are stored an hour earlier, since we were supposed to be in DST if it weren't for changes in 2019.

My hypothesis is that the problem is in the synchronization phase, where MineTime parses all of the events using `pytz` to handle timezones. Maybe `pytz`'s dependency has an outdated version and could use some updates? They seem to have updated their timezone info in mid-2019 and this app is certainly older than that.

@marcoancona could you please investigate if that is the case?

P.S.: Althought this problem does make the app unusable for now, I really love it and it was my daily driver for a long time until November haha. Thanks for the wonderful work and I would certainly contribute if I could!

**Comment by mikaelmello** [comment] 2020-12-16 23:33
I am glad to say this issue appears to be fixed on 1.9.0 @jvgirard

**Comment by marcoancona** [comment] 2020-12-16 23:46
We have updated the times one days in 1.9.0. Glad to hear that the problem with Brazilian time is fixed. Feel free to comment if the issue persists.

**Closed** 2020-12-16 23:46 UTC
