### ISSUE TITLE
Can't connect to Google Calendar (with proxy)

### ISSUE THREAD

**Issue by tankgit** [marcoancona/MineTime#52] opened 2018-07-28 12:05 UTC
I can add my MS account and maybe other types, but every time when I'm adding my google calendar, after verifying at the pop-up window(authentication page), it just closed, returned back to the account-choose dialog, as the following image, without anything changed in MineTime app.
![image](https://user-images.githubusercontent.com/7694464/43356324-27f362d2-92a1-11e8-9986-830f7118cddb.png)

Env: ubuntu 18.04, amd64, gnome-shell 3.28, installed from the latest deb package on official website.

**Comment by lucasczpnk** [comment] 2018-08-01 05:12
I'm having the same issue, also using 18.04!

**Comment by marcoancona** [comment] 2018-08-01 11:42
We cannot reproduce the problem. We experience no issues with Google accounts on Ubuntu 18.04 with MineTime 1.3.1. Can you check MineTime is listed in the apps with access to your calendar account in https://myaccount.google.com/permissions ?
About iCloud, @lucasczpnk are you using a dedicated app-specific password?

**Comment by tankgit** [comment] 2018-08-01 15:51
It isn't listed in my google permission list. I tried turn down the security level(allow access for low security app), but no use.
I tried several google accounts, none of them worked.
I just wonder how can I open the authentication page in chrome, or is there any log files? Then maybe I can figure out what's going on.

**Comment by marcoancona** [comment] 2018-08-01 15:59
You can try to type `analysis` in the assistant input area. This will open the Chrome dev tools and show the logs. Setting `allow access for low security app` is not necessary for MineTime and I would recommend to switch it on again.
Do you connect via a proxy?

**Comment by tankgit** [comment] 2018-08-02 02:59
Yes, I use socks5, and set it to global in system proxy settings since my location is restricted with connecting google service.

**Comment by esonn** [comment] 2018-08-02 08:19
Had the same issue on a newly installed Arch Linux - gnome-keyring must be installed for managing secrets, worked afterwards.

**Comment by marcoancona** [comment] 2018-08-02 09:12
@esonn : thanks for pointing out. We'll have to fix this, however without gnome-keyring you wouldn't have been able to set up any of the services - not only Google - so it cannot explain this issue.
@tankgit : the proxy can explain the issue, as we have not investigated support for proxy at the moment. Which os are you using? Can you check your environment has `HTTP_PROXY / http_proxy` and `HTTPS_PROXY / https_proxy` variables set?

**Comment by tankgit** [comment] 2018-08-02 09:52
@marcoancona ubuntu, and yes, I set variables, I tried `ALL_PROXY`/`HTTP_PROXY`/`HTTPS_PROXY`, still not work. I'm afraid it's not proxy issues since I can access the login page of google account (which I cannot open if I don't use proxy).
So weird, I give up, just use MS account..sigh...

**Comment by marcoancona** [comment] 2018-08-02 10:45
The front-end Chromium process handles proxy settings independently of the backend libraries. The problem is *not* the proxy or its configuration, but that the API libraries fail to use those settings. I think this is related to https://github.com/google/google-api-nodejs-client/issues/998, which has now high priority and hopefully fixed soon.

**Comment by ashwoods** [comment] 2018-08-27 17:05
I'm having a similar problem with OSX and minetime 1.4, no proxy usage. MineTime just dies.

**Comment by marcoancona** [comment] 2018-08-27 17:16
Could you be more precise about "just dies"? Do you manage to visualize the Google login view?

**Comment by ashwoods** [comment] 2018-08-27 20:20
Yes I manage to visualize the google login view, log in, give it permissions. Verfified the permissions are given on the google panel.  MineTime google auth screen just closes, app becomes slower and slower, and then crashes. https://gist.github.com/ashwoods/b443ca230aa176694295c4ab432be71a

**Comment by ashwoods** [comment] 2018-08-27 20:32
Tracked the problem to Sophos web protection. :/

**Comment by marcoancona** [comment] 2018-08-29 07:40
Thanks, we will investigate. Then this is not related to the original issue reported here. The problem with MineTime crashing when the network in not available (or blocked) will be fixed in the next release.

**Closed** 2018-09-30 17:47 UTC
Labels: bug, external
