### ISSUE TITLE
Keeps sending notification for the same event at ~1 sec intervals

### ISSUE THREAD

**Issue by lm808** [marcoancona/MineTime#67] opened 2018-09-01 21:46 UTC
MineTime (v1.4.1) keeps reminding me, via desktop notifications, about an event that is happening in 25 days. The event was set to alert 1 hour before the event. The notifications were sent at roughly 1 sec intervals. The following stopped the notifications:
1) Turning alert off for the event
2) Moving the event to 1 day before
3) Moving the event 3 days afterwards (moving it 1-2 days after simply changes the message "starts in 25 days" to "starts in a month").
4) Move the event to 1 day before (say, 26th) & create a new event with the same parameters on the original day (27th) will not trigger the alert. However, if you delete the original event (now moved to 26th), the newly created event (on 27th) will again cause non-stopping alerts.

In addition, moving it from Office 356 to iCloud did not help.
OS: Arch Linux + xfce4

Console output each time when an alert is fired:
```
tmp: onAlert fired, events [{"_id":"5b8b075de2e4b007dc4fef94","attendees":[],"location":{"t":""},"accountId":"5b773d6a6b0e16105d795128","calendarId":"5b773d6a6b0e16105d795129","dtstamp":"2018-09-01T21:42:44.398Z","created":"2018-09-01T21:40:44.000Z","lastmodified":"2018-09-01T21:42:43.000Z","providerId":"AAMkADYxNzVmZGNkLWU5NzYtNGFhNy1iODJmLTA3ZGQ4MDBjMzdmNgBGAAAAAAC06qTyuadSRZ1dbiSNXRyBBwC3kZg62elpQbLvXFJhxTc3AAADLXDoAAAhxtK0/HdmRrvvztEuRgKiAAKaxKYvAAA=","iCalUid":"040000008200E00074C5B7101A82E008000000000132F76F3C42D4010000000000000000100000009E4C1807B22FB34CB107640A0CB56B29","summary":"Departmental Assembly","dtstart":{"date":"2018-09-27T01:00:00.000Z","isDay":false,"tz":0},"dtend":{"date":"2018-09-27T02:00:00.000Z","isDay":false,"tz":0},"timezone":"Europe/London","organizer":{"uri":"[*user info redacted*]","email":"[*user info redacted*]","cn":"[*user info redacted*]","isMe":true,"isSelf":true},"reminder":[15],"ews-AppointmentType":"Single","ews-AppointmentState":1,"ews-Importance":"Normal","ews-Sensitivity":"Normal","_rc":false,"effectiveStart":{"date":"2018-09-27T01:00:00.000Z","isDay":false,"tz":0},"effectiveEnd":{"date":"2018-09-27T02:00:00.000Z","isDay":false,"tz":0}}]
```

**Comment by marcoancona** [comment] 2018-09-06 10:39
We are investigating the issue but we could not reproduce it at the moment. Did it happen with other events as well?

**Comment by marcoancona** [comment] 2018-11-19 18:34
I will close this, as there was no further reports of similar problems.

**Closed by marcoancona** 2018-11-19 18:34 UTC
Labels: bug
