### ISSUE TITLE
CalDAV account linking issue

### ISSUE THREAD

**Issue by bayang** [marcoancona/MineTime#19] opened 2018-02-23 11:16 UTC
It says authentication failed
I tried with the different types of urls available : 

https://framagenda.org/remote.php/dav/
https://framagenda.org/remote.php/dav/principals/users/toto/

and the direct url to the calendar.

**Comment by MSSandroid** [comment] 2018-02-24 14:55
For me https://<domain>/remote.php/dav/ authenitcates and i can see the right calenders. 
But it does not seem to fetch the events. It infinitly shows loading circles next to the calenders and no event is displayed

**Comment by marcoancona** [comment] 2018-03-14 17:53
Hello,
we have just tried to create an account on framagenda.org and the connection to the DAV service using the latest version of MineTime had not apparent issue, using the Principal url (`https://framagenda.org/remote.php/dav/`). Syncing also seems to work but we could only test manually a few events.
Does the problem persist? Which version of MineTime and Operating system are you using?

**Comment by bayang** [comment] 2018-03-15 15:43
I'm using ubuntu 17.10 and MineTime 1.1.3, still not working when using the same url as you...

**Comment by bayang** [comment] 2018-07-13 07:51
I tried with 1.3.1 but still the same problem.
In the meantime I switched a while ago to a google calendar instead and this is working fine.

**Comment by marcoancona** [comment] 2018-09-06 10:44
@MSSandroid : which os are you using? Issue possibly related to #55. Please make sure you have `gnome-keyring` installed.
@bayang : version 1.4.1 now solves #58 as well, which might have been the cause of the issue with framagenda.

**Comment by TraceyC77** [comment] 2018-09-24 12:17
I had this issue with my personal NextCloud instance as well. It seems the root issue is that MineTime is not able to auto-discover the calendar URL from the main server URL as other clients can. If the full URL to the calendar is necessary, this should be noted in text on the login UI. Ideally building support for discovery would be better.

This URL did not work:
https://nextcloud.example.com

This URL worked.
https://nextcloud.example.com/remote.php/dav/calendars/username/personal/

**Comment by marcoancona** [comment] 2018-09-24 15:06
Yes, we are working on autodiscover. Same issue if using https://calendar.zoho.com instead of https://calendar.zoho.com/caldav

**Comment by Kalkihe** [comment] 2018-11-14 09:58
> I had this issue with my personal NextCloud instance as well. It seems the root issue is that MineTime is not able to auto-discover the calendar URL from the main server URL as other clients can. If the full URL to the calendar is necessary, this should be noted in text on the login UI. Ideally building support for discovery would be better.
> 
> This URL did not work:
> https://nextcloud.example.com
> 
> This URL worked.
> https://nextcloud.example.com/remote.php/dav/calendars/username/personal/

I tried both urls, neither of them didn't work for me.

**Comment by marcoancona** [comment] 2018-11-18 10:05
This looks like a connectivity issue. Which version of MineTime are you running? Are you working behind a proxy?

**Comment by marcoancona** [comment] 2018-11-19 18:32
This issue is quite old and many improvements has been made since the first post. 
Lately, most of the issues are cause by:
- wrong server URL (we are still working on DAV autodiscovery, so please try your Principal URL for now)
- missing `gnome-keyring` (Linux).
- other connectivity problems not related to MineTime

I will close this issue for now. If you find a DAV account that does not work with MineTime and the reason is none of the above, please open a new issue.

**Closed by marcoancona** 2018-11-19 18:32 UTC

**Comment by davigega** [comment] 2020-05-05 20:25
Hello!
this might be an old issue, but I'm experiencing it right now. 
url is an owncloud server:
https://www.example.eu/owncloud/remote.php/dav/

- server address double checked
- libsecret installed
- no connectivity issues.

The thing is that it just happened after a while. I've been working fine with 1.7.4 and one day it just couldn't connect to the server any more...
I just upgraded to minetime 1.7.6 on debian testing with no result

**Comment by nicosomb** [comment] 2020-10-05 12:32
I found the issue. 
I had the TOTP feature enabled and it failed. 

When I disable it, MineTime manages to fetch my caldav calendar.
