### ISSUE TITLE
Database port should be selected dynamically

### ISSUE THREAD

**Issue by skalarproduktraum** [marcoancona/MineTime#177] opened 2020-03-02 13:07 UTC
Hi there,

I'm having the issue that after adding two accounts, MineTime doesn't show them any more, and the calendar view is also empty, showing only a loading animation. The backend log only states lots of...

```
2020-03-02T13:04:42.180Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
```

I also cannot open the frontend log by typing `analysis` (nice one, btw) into the assistant -- there's just nothing happening then. Any suggestions? I also noticed there should probably be mongod running, although I couldn't find that process. OS is Windows 10. Any ideas?

Thanks!

**Comment by marcoancona** [comment] 2020-03-02 15:04
Hi,
indeed it looks it cannot connect to the database.
Did it work in the  past? Did you try restarting MineTime (by killing all the processes related to it, maybe some are hanging). The debug command is now `#analysis`.

**Comment by skalarproduktraum** [comment] 2020-03-02 15:26
Hi,
I worked briefly. I tried restarting (several times, actually), `#analysis` also doesn't work. Should there be a `mongod` process running?

**Comment by marcoancona** [comment] 2020-03-02 15:27
Yes, there should be. Which version of MineTime are you using?

**Comment by skalarproduktraum** [comment] 2020-03-02 15:28
This is version 1.7.6.

**Comment by skalarproduktraum** [comment] 2020-03-02 15:45
Okay, it seems like mongodb can't bind to the port it wants to. I've tried now starting this manually:

```
$ ./win64/mongod.exe --config ../mongo/mongod.conf --dbpath C:\\redacted\\AppData\\Roaming\\MineTime\\calendars --port 50060
2020-03-02T16:42:23.233+0100 I CONTROL  [initandlisten] MongoDB starting : pid=24324 port=50060 dbpath=C:\redacted\AppData\Roaming\MineTime\calendars 64-bit host=DESKTOP-NJU45J2
2020-03-02T16:42:23.233+0100 I CONTROL  [initandlisten] targetMinOS: Windows Vista/Windows Server 2008
2020-03-02T16:42:23.234+0100 I CONTROL  [initandlisten] db version v3.4.2
2020-03-02T16:42:23.234+0100 I CONTROL  [initandlisten] git version: 3f76e40c105fc223b3e5aac3e20dcd026b83b38b
2020-03-02T16:42:23.234+0100 I CONTROL  [initandlisten] allocator: tcmalloc
2020-03-02T16:42:23.234+0100 I CONTROL  [initandlisten] modules: none
2020-03-02T16:42:23.234+0100 I CONTROL  [initandlisten] build environment:
2020-03-02T16:42:23.235+0100 I CONTROL  [initandlisten]     distarch: x86_64
2020-03-02T16:42:23.235+0100 I CONTROL  [initandlisten]     target_arch: x86_64
2020-03-02T16:42:23.235+0100 I CONTROL  [initandlisten] options: { config: "../mongo/mongod.conf", net: { bindIp: "127.0.0.1", port: 50060 }, storage: { dbPath: "C:\redacted\AppData\Roaming\MineTime\calendars" } }
2020-03-02T16:42:23.236+0100 E NETWORK  [initandlisten] listen(): bind() failed An attempt was made to access a socket in a way forbidden by its access permissions. for socket: 127.0.0.1:50060
2020-03-02T16:42:23.236+0100 E NETWORK  [initandlisten] Failed to set up sockets during startup.
2020-03-02T16:42:23.236+0100 E STORAGE  [initandlisten] Failed to set up listener: InternalError: Failed to set up sockets
2020-03-02T16:42:23.236+0100 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2020-03-02T16:42:23.236+0100 I NETWORK  [initandlisten] shutdown: going to flush diaglog...
2020-03-02T16:42:23.237+0100 I CONTROL  [initandlisten] now exiting
2020-03-02T16:42:23.237+0100 I CONTROL  [initandlisten] shutting down with code:48
```

I presume there's no fallback if that port doesn't work?

**Comment by skalarproduktraum** [comment] 2020-03-02 15:52
Okay, further investigation yields this: You can apparently block ports for assignment:

```
$ netsh interface ipv4 show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      5357        5357
      5700        5700
      8884        8884
      9001        9001
     28385       28385
     49757       49856
     50000       50059     *
     50060       50159
     50160       50259
     50260       50359
     50360       50459
     50460       50559
     50560       50659
     50660       50759
     50764       50863

* - Administered port exclusions.
```

Mostly, these come from Hyper-V or Docker. Now the question is, @marcoancona, is there a way to change the port used by mongod? I think the best way would actually be to try to actively find one that works. 

On a somewhat related note, if the software were already open-sourced, I'd have been delighted to contribute a fix for the issue 😉

**Comment by marcoancona** [comment] 2020-03-02 15:53
Thanks for investigating. This is interesting indeed. We are aware of a possible issue if the port is in use (and we have already dynamic port selection in our roadmap) but this seems to be something different. [This](https://appuals.com/fix-an-attempt-was-made-to-access-a-socket-in-a-way-forbidden-by-its-access-permissions/) lists possible causes, including some security feature on Windows 10. However, our test machine with Windows 10 works without additional configuration so this would require further investigation.

**Comment by skalarproduktraum** [comment] 2020-03-02 15:58
Try enabling Hyper-V (and maybe install Docker for Windows). 

Also, the site you linked has a lot of clickbait, looks like a content mill, and suggests crapware (_TIP: If none of the Methods have resolved the issue for you, we recommend using Reimage Repair Tool which can scan the repositories to replace corrupt and missing files..._).

**Comment by skalarproduktraum** [comment] 2020-03-02 16:01
However, that is unfortunately not the main issue here. That port might be unavailable for a lot of reasons. So the solution would be to not rely on it being available, but falling back to an alternative (or multiple). Is there a config options in `config.json` or so to set it to another port?

**Comment by marcoancona** [comment] 2020-03-02 16:06
> Okay, further investigation yields this: You can apparently block ports for assignment:
> 
> ```
> $ netsh interface ipv4 show excludedportrange protocol=tcp
> 
> Protocol tcp Port Exclusion Ranges
> 
> Start Port    End Port
> ----------    --------
>       5357        5357
>       5700        5700
>       8884        8884
>       9001        9001
>      28385       28385
>      49757       49856
>      50000       50059     *
>      50060       50159
>      50160       50259
>      50260       50359
>      50360       50459
>      50460       50559
>      50560       50659
>      50660       50759
>      50764       50863
> 
> * - Administered port exclusions.
> ```
> 
> Mostly, these come from Hyper-V or Docker. Now the question is, @marcoancona, is there a way to change the port used by mongod? I think the best way would actually be to try to actively find one that works.
> 
> On a somewhat related note, if the software were already open-sourced, I'd have been delighted to contribute a fix for the issue

Unfortunately, there is no easy workaround then as the `mongod` port is fixed. I will make this a high priority fix.

> Also, the site you linked has a lot of clickbait, looks like a content mill, and suggests crapware (_TIP: If none of the Methods have resolved the issue for you, we recommend using Reimage Repair Tool which can scan the repositories to replace corrupt and missing files..._).

Agree, but was not intended as ultimate solution for the problem.

**Comment by skalarproduktraum** [comment] 2020-03-02 16:22
Temporary but ugly fix: Unpacked the app.asar file, changed the port to something that is not excluded, repacked -> works again.

**Comment by marcoancona** [comment] 2020-03-02 16:25
> Temporary but ugly fix: Unpacked the app.asar file, changed the port to something that is not excluded, repacked -> works again.

Pretty hacky but glad it worked! :-)

**Comment by skalarproduktraum** [comment] 2020-03-02 16:26
Maybe a quicker fix than dynamic port selection would be to get the port from an environment var (`MINETIME_MONGOD_PORT` or sth) if set 👍

**Comment by skalarproduktraum** [comment] 2020-03-02 16:30
Also sorry for being critical before, I think MineTime is a great app, and the calendar app on Windows 10 I like most at the moment 👍 Keep up the good work!

**Comment by marcoancona** [comment] 2020-03-02 22:25
No offence taken. Thanks for debugging the problem 👍

**Comment by brabitom** [comment] 2020-03-06 09:54
> 
> Temporary but ugly fix: Unpacked the app.asar file, changed the port in `minemongo.js` to something that is not excluded, repacked -> works again.

Hi, I had same problem on Windows 10. After manually change the port in minemongo.js, MineTime works correctly.

**Comment by eikaramba** [comment] 2020-04-08 11:09
finally someone with the same problem. i have this problems since months, that a lot of times minetime does not work and is not showing anything. i found the logs and then this thread. i don't have anything blocking the port, but also have hyper-v so maybe that's it.

Repacking the app.asar file with a different port also fixed it for me!!
FYI: For anyone not knowing how to unpack/pack the app.asar file, look here https://stackoverflow.com/questions/38523617/how-to-unpack-an-asar-file

**Comment by marcoancona** [comment] 2020-06-26 08:28
Release 1.8.0 uses dynamic port selection for the database. I will close this issue. Feel free to comment if the problem persists.

**Comment by eikaramba** [comment] 2020-06-26 11:42
i upgraded to 1.8.0 but unfortunately the problem is still there. Nothing is loading anymore.

**Comment by eikaramba** [comment] 2020-06-26 12:02
also the trick from above does not seem to work anymore when i unpack, change port and pack again the program is not starting at all anymore

**Comment by marcoancona** [comment] 2020-06-26 14:22
Could you please check in the task manager that there are no instances of `mongod` running when you close MineTime?

**Comment by marcoancona** [comment] 2020-06-26 14:28
Ok, it appears that `get-port` (on which 1.8.0 relies) is affected by false positives: https://github.com/sindresorhus/get-port/issues/48

**Comment by marcoancona** [comment] 2020-06-26 15:52
We quickly recompiled with a different configuration to find one available port. It would be really useful to know if this works: https://storage.googleapis.com/minetime-temp-artifacts/MineTime-Setup-1.8.1.exe

**Comment by eikaramba** [comment] 2020-06-27 15:13
sry was enjoing the weather yesterday. so yes i made sure mongodb is not running or anything. it does not work and as i said the quickfix from above seems to not work anymore.

Unfortunately also Version 1.8.1 does not work as well. I also don't see anything in the logs:
```
2020-06-27T15:04:51.156Z - info: Update for version 1.8.0 is not available (latest version: 1.8.0, downgrade is disallowed).
2020-06-27T15:04:51.156Z - info: Updater: update-not-available
2020-06-27T15:10:32.474Z - info:  
2020-06-27T15:10:32.475Z - info: *********************
2020-06-27T15:10:32.475Z - info: App ready
2020-06-27T15:10:32.476Z - info:  0=C:\Users\thies\AppData\Local\Programs\MineTime\MineTime.exe
2020-06-27T15:10:32.476Z - info: *********************

2020-06-27T15:10:32.559Z - info: Checking for update
2020-06-27T15:10:32.559Z - info: Updater: checking-for-update
2020-06-27T15:10:32.559Z - info: Updater: checking-for-update
2020-06-27T15:10:32.637Z - error:  message=DELETE command exited with code 1:

FEHLER: Der angegebene Registrierungsschl�ssel bzw. Wert wurde nicht gefunden., stack=ProcessUncleanExitError: DELETE command exited with code 1:

FEHLER: Der angegebene Registrierungsschl�ssel bzw. Wert wurde nicht gefunden.
    at mkErrorMsg (C:\Users\thies\AppData\Local\Programs\MineTime\resources\app.asar\node_modules\winreg\lib\registry.js:111:12)
    at ChildProcess.<anonymous> (C:\Users\thies\AppData\Local\Programs\MineTime\resources\app.asar\node_modules\winreg\lib\registry.js:771:10)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12), name=ProcessUncleanExitError, code=1
2020-06-27T15:10:35.422Z - info: Update for version 1.8.1 is not available (latest version: 1.8.0, downgrade is disallowed).
2020-06-27T15:10:35.422Z - info: Updater: update-not-available
```

The registry error was already there for months and should not be the problem as it worked before upgrading to 1.8.0 even with that strange error (just noticed it when copying the log files)
Is there anything else i should try? I'm a javascript developer myself....

**Comment by marcoancona** [comment] 2020-06-27 16:42
When you say "nothing is loading" you mean that events do not appear or that the main window does not appear? If that is all the log you get, it seems that the problem after upgrading to 1.8.0 is something else than the connection to the db.

**Comment by eikaramba** [comment] 2020-06-27 16:46
no it is the same problem that was there for at least a year before i discovered this fix in this thread. no data is shown but the ui is there.
![ns2VoJAL16](https://user-images.githubusercontent.com/1320525/85927467-8a253e80-b8a6-11ea-9ce6-ec28711b93a2.gif)

**Comment by marcoancona** [comment] 2020-06-27 22:17
Ok, here is what I suggest:
- try this new build: https://storage.googleapis.com/minetime-temp-artifacts/MineTime-Setup-1.8.1.RC2.exe
- if the problems still persist, you can apply the hack before but you need to make sure you assign the `port` variable directly to bypass the automatic port selection

Thanks for helping out debugging this.

**Comment by eikaramba** [comment] 2020-06-27 22:20
1.8.1 RC2 works out of the box! Yesssssss thank you.

**Comment by marcoancona** [comment] 2020-06-27 22:56
🎉  I will close here then!

**Closed** 2020-06-27 22:56 UTC
Labels: enhancement

**Comment by skalarproduktraum** [comment] 2020-06-30 11:01
Thanks for fixing this! 👍
