### ISSUE TITLE
source links 

### ISSUE THREAD

**Issue by phwelo** [marcoancona/MineTime#17] opened 2018-01-31 15:16 UTC
on [the releases page](https://github.com/marcoancona/MineTime/releases) source packages are empty besides one readme file.

[Source code (zip)](https://github.com/marcoancona/MineTime/archive/v1.1.0.zip)
[Source code (tar.gz)](https://github.com/marcoancona/MineTime/archive/v1.1.0.tar.gz)

**Comment by marcoancona** [comment] 2018-01-31 15:28
This is intended. MineTime is is free but *not* open-source (yet). Source code packages are automatically created by Github when a new release is published but they are empty. I close this.

**Closed by marcoancona** 2018-01-31 15:28 UTC

**Comment by phwelo** [comment] 2018-02-01 21:35
ah my bad, I guess I don't spend much time looking at closed-source stuff
on Github! Hopefully you do decide to open source eventually!

**Comment by alexanderadam** [comment] 2020-07-23 07:56
Duplicate of #3
