### ISSUE TITLE
Crash while installing

### ISSUE THREAD

**Issue by a1346054** [marcoancona/MineTime#126] opened 2019-07-03 23:44 UTC
`2019-07-03 23:37:45> Program: Starting Squirrel Updater: --install .
2019-07-03 23:37:47> Program: Starting install, writing to C:\Users\user\AppData\Local\SquirrelTemp
2019-07-03 23:37:47> Program: About to install to: C:\Users\user\AppData\Local\MineTime
2019-07-03 23:37:53> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user\AppData\Local\MineTime\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-07-03 23:37:53> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user\AppData\Local\MineTime\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-07-03 23:37:53> CheckForUpdateImpl: Reading RELEASES file from C:\Users\user\AppData\Local\SquirrelTemp
2019-07-03 23:37:54> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-07-03 23:37:59> ApplyReleasesImpl: Writing files to app directory: C:\Users\user\AppData\Local\MineTime\app-1.5.1
2019-07-03 23:38:11> LogHost: Rigging execution stub for lib/net45/MineTime_ExecutionStub.exe to C:\Users\user\AppData\Local\MineTime\MineTime.exe
2019-07-03 23:38:13> LogHost: Rigging execution stub for lib/net45/resources/app.asar.unpacked/node_modules/node-notifier/vendor/snoreToast/SnoreToast_ExecutionStub.exe to C:\Users\user\AppData\Local\MineTime\app-1.5.1\resources\app.asar.unpacked\node_modules\node-notifier\vendor\SnoreToast.exe
2019-07-03 23:38:14> LogHost: Rigging execution stub for lib/net45/resources/app.asar.unpacked/node_modules/node-notifier/vendor/notifu/notifu_ExecutionStub.exe to C:\Users\user\AppData\Local\MineTime\app-1.5.1\resources\app.asar.unpacked\node_modules\node-notifier\vendor\notifu.exe
2019-07-03 23:38:14> LogHost: Rigging execution stub for lib/net45/resources/app.asar.unpacked/node_modules/node-notifier/vendor/notifu/notifu64_ExecutionStub.exe to C:\Users\user\AppData\Local\MineTime\app-1.5.1\resources\app.asar.unpacked\node_modules\node-notifier\vendor\notifu64.exe
2019-07-03 23:38:15> LogHost: Rigging execution stub for lib/net45/resources/app.asar.unpacked/node_modules/7zip-bin-win/x64/7za_ExecutionStub.exe to C:\Users\user\AppData\Local\MineTime\app-1.5.1\resources\app.asar.unpacked\node_modules\7zip-bin-win\7za.exe
2019-07-03 23:38:15> LogHost: Rigging execution stub for lib/net45/resources/app.asar.unpacked/node2: System.IO.IOException: The process cannot access the file 'C:\Users\user\AppData\Local\Temp\.squirrel-lock-33D2F84D2ED34464C7935FB4A742B30B1AD2C472' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2019-07-03 23:37:54> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\user\AppData\Local\Temp\.squirrel-lock-33D2F84D2ED34464C7935FB4A742B30B1AD2C472: System.IO.IOException: The process cannot access the file 'C:\Users\user\AppData\Local\Temp\.squirrel-lock-33D2F84D2ED34464C7935FB4A742B30B1AD2C472' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2019-07-03 23:37:54> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\user\AppData\Local\Temp\.squirrel-lock-33D2F84D2ED34464C7935FB4A742B30B1AD2C472: System.IO.IOException: The process cannot access the file 'C:\Users\user\AppData\Local\Temp\.squirrel-lock-33D2F84D2ED34464C7935FB4A742B30B1AD2C472' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2019-07-03 23:37:55> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\user\AppData\Local\Temp\.squirrel-lock-33D2F84D2ED34464C7935FB4A742B30B1AD2C472: System.IO.IOException: The process cannot access the file 'C:\Users\user\AppData\Local\Temp\.squirrel-lock-33D2F84D2ED34464C7935FB4A742B30B1AD2C472' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2019-07-03 23:37:57> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

`

**Comment by marcoancona** [comment] 2019-09-03 15:22
Could not reproduce. The new 1.6.1 ships with a new installer. Could you please try this one?

**Comment by marcoancona** [comment] 2019-10-16 18:01
Need migration to NSIS
https://github.com/electron-userland/electron-builder/issues/1171

**Comment by marcoancona** [comment] 2019-10-17 21:11
Duplicate of #136. Discussion and solution will continue there.

**Closed by marcoancona** 2019-10-17 21:11 UTC
