### ISSUE TITLE
Cannot login to Office365 Corporate account 

### ISSUE THREAD

**Issue by pablorq** [marcoancona/MineTime#231] opened 2020-09-21 17:01 UTC
When I try to connect to a Corporate Office365 account, it goes from MineTime to the browser and start the Office365 login process but after a few clicks it says the administrator has to grant access to MineTime and the login process can't be finished.

I'm using Ubuntu 20.04 + MineTime v1.8.6. I tested the same MineTime version on Windows10 and I was able to login to the same Corpote Office365 account.

Any ideas?

**Comment by marcoancona** [comment] 2020-09-21 20:13
Hello,
do I understand correctly that the same version of MineTime works on Windows 10 but not on Ubuntu? From your description, it looks like the problem arises on the Office 365 side. Maybe the administrator has disabled the access from some operating system or browser?

**Comment by pablorq** [comment] 2020-09-22 12:41
Hi,

Yes, you've understand it right. It's strange. And I don't know if is it possible to disable the access for OS.

But I've found a workaround [here](https://stackoverflow.com/questions/50327827/gnome-calendar-and-office-365-calendar). This is a solution to use an Exchange server with Gnome's calendar app.

So I tried it on MineTime with the following data:

- Service: Exchange
- email: [my email]
- password: [my password]
- exchange user: [my email]
- server: **outlook.office365.com**

MineTime was able to connect and now it shows an Office365 icon account.

The server info did the trick!

---
(I left this issue open for further questions. Otherwise, please close it.)

**Comment by marcoancona** [comment] 2020-09-28 14:25
I will close this issue as the problem is likely due to some policy of Conditional Access for Office 365 (https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-conditions)

**Closed by marcoancona** 2020-09-28 14:25 UTC
Labels: investigate
