### ISSUE TITLE
Etesync-DAV

### ISSUE THREAD

**Issue by bennypr0fane** [marcoancona/MineTime#251] opened 2020-12-02 13:55 UTC
Hello,
I want to use MineTime on my Linux PCs with Etesync, which is an end-to-end encrytped protocol for calendar/tasks/contact sync. It has an adapter for CalDAV (Etesync-dav) which is installed locally, connects to the Etesync server and serves CalDAV sync to client apps.
I set it up in Minetime on 2 Linux PCs, and a new CalDAV calendar does appear for me in MineTime, but events were at first not visible. Now, events from the Etesync calendar just popped up after a couple days on one of the PCs, but it's still emtpy on the other.
I tried subscribing to a couple other CalDAV syncs from different sources, which worked.
Does MineTime have tools like e.g. logs to diagnose what's happening when in syncs and why events aren't showing?

**Comment by marcoancona** [comment] 2020-12-08 08:19
We have planned support to Etesync with the next major version coming early next year.

**Comment by marcoancona** [comment] 2020-12-08 08:21
Closing as duplicate of #243

**Closed by marcoancona** 2020-12-08 08:21 UTC
