### ISSUE TITLE
No source code for v1.4.5

### ISSUE THREAD

**Issue by dilyanpalauzov** [marcoancona/MineTime#85] opened 2018-10-19 12:40 UTC
The “source code” at https://github.com/marcoancona/MineTime/releases/tag/v1.4.5 does not include any source code, only a README.md file.

**Comment by marcoancona** [comment] 2018-10-19 13:02
Duplicate of #3 . MineTime is not (yet) an open-source project.

**Closed by marcoancona** 2018-10-19 13:02 UTC
